import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${montserrat.className} bg-stone-50 dark:bg-stone-950 text-stone-950 dark:text-stone-50`}>
                {/* <header className="w-full bg-slate-500 h-24">Hola</header> */}
                {children}
            </body>
        </html>
    );
}
